issues:
  exclude-use-default: false
  max-same-issues: 0
linters:
  enable:
    - dupl
    - copyloopvar
    - gochecknoinits
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - stylecheck
    - unconvert
    - unparam
  disable:
    - errcheck
