---
project_name: prometheus-nats-exporter

release:
  draft: true
  github:
    owner: nats-io
    name: prometheus-nats-exporter

  name_template: 'Release {{.Tag}}'

env:
  - IMAGE_REPOSITORY={{ if index .Env "IMAGE_REGISTRY" }}{{ .Env.IMAGE_REGISTRY }}/{{ end }}{{ .ProjectName }}

builds:
  - id: prometheus-nats-exporter
    main: .
    binary: prometheus-nats-exporter
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
    - darwin
    - linux
    - windows
    - freebsd
    goarch:
    - amd64
    - arm
    - arm64
    - 386
    - mips64le
    goarm:
    - 6
    - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: 386

archives:
  - name_template: '{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}'
    wrap_in_directory: true
    format: zip
    files:
      - README.md
      - LICENSE
  - name_template: '{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}'
    id: targz-archives
    wrap_in_directory: true
    format: tar.gz
    files:
      - README.md
      - LICENSE

checksum:
  name_template: '{{ .ProjectName }}-v{{ .Version }}-checksums.txt'

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

nfpms:
  - file_name_template: '{{.ProjectName}}-{{.Tag}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}'
    homepage:  https://nats.io
    description: A Prometheus exporter for NATS
    maintainer: Colin Sullivan <colin@nats.io>
    vendor: nats.io
    license: Apache 2.0
    formats:
    - deb
