#syntax=docker/dockerfile:1.13
FROM --platform=$BUILDPLATFORM golang:1.25.8-trixie AS build

ARG GITHUB_RUN_ID

RUN <<EOT
  set -e

  echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' > /etc/apt/sources.list.d/goreleaser.list
  apt-get update
  apt-get install -y goreleaser
  rm -rf /var/lib/apt/lists/*
EOT

FROM build

ARG CI
ARG GITHUB_TOKEN
ARG SNAPSHOT=true

COPY --from=src . /go/src

WORKDIR /go/src

RUN --mount=type=cache,target=/go/pkg/mod <<EOT
  set -e
  go mod download
EOT

RUN --mount=type=cache,target=/go/pkg/mod <<EOT
  set -e

  FLAGS="--clean"
  if [ -n "${GITHUB_TOKEN}" ]; then
    goreleaser release ${FLAGS}
  else
    if [ "${SNAPSHOT}" = "true" ]; then
      FLAGS="${FLAGS} --snapshot"
    fi
    if [ "${CI}" != "true" ]; then
      FLAGS="${FLAGS} --skip=validate --single-target"
    fi
    goreleaser build ${FLAGS}
  fi
EOT
