#syntax=docker/dockerfile-upstream:1.5
FROM --platform=$BUILDPLATFORM golang:1.23.0-bullseye as build

RUN <<EOT
    set -e

    echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' > /etc/apt/sources.list.d/goreleaser.list
    apt-get update
    apt-get install -y goreleaser
    rm -rf /var/lib/apt/lists/*
EOT

FROM build

ARG CI
ARG GITHUB_TOKEN

COPY --from=src . /go/src

RUN <<EOT
  set -e
  cd /go/src
  FLAGS="--clean"
  if [ -z ${GITHUB_TOKEN} ]; then
    if [ ${CI} != "true" ]; then FLAGS="${FLAGS} --skip-validate --single-target"; fi
    goreleaser build ${FLAGS}
  else
    goreleaser release ${FLAGS}
  fi
EOT
