name: Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions: {}

# This would trigger if we ... move a release tag?  Ugh.  Would prefer to flag that as a poisoning error and kill all builds.
# We'll settle for killing the prior one.
# This should resolve a Zizmor v1.16+ "concurrency-limits" check.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # goreleaser (inside bake) release assets upload
      # The images are pushed to DockerHub via static secret, so we don't need packages:write here

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Setup QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Setup Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_CLI_TOKEN }}

      - name: Get Image Tags
        id: tags
        run: |
          version=$(sed 's/^v//' <<< "${GITHUB_REF_NAME}")
          echo tags="latest,${version}" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/bake-action@a66e1c87e2eca0503c343edf1d208c716d54b8a8 # v7.1.0
        env:
          TAGS: "${{ steps.tags.outputs.tags }}"
          REGISTRY: "natsio"
          SNAPSHOT: "false"
          GITHUB_RUN_ID: "${{ github.run_id }}"
        with:
          source: .
          files: docker-bake.hcl
          push: true
          set: |
            goreleaser.args.GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
